# debug_cp1.py
# Debug CP1 (Landmarks) mismatch
# CP1（ランドマーク）不一致のデバッグ

import pandas as pd
import numpy as np

# Load dumps
df_gt = pd.read_csv('dump_openface.csv', header=None, names=['FrameID','CP','Idx','Val'])
df_tg = pd.read_csv('dump_recover.csv', header=None, names=['FrameID','CP','Idx','Val'])

print("=" * 70)
print("CP1 (Landmarks) Debug Analysis")
print("=" * 70)

# Get CP1 data
cp1_gt = df_gt[df_gt['CP']=='CP1'].sort_values(['FrameID', 'Idx'])
cp1_tg = df_tg[df_tg['CP']=='CP1'].sort_values(['FrameID', 'Idx'])

print(f"CP1 GT rows: {len(cp1_gt)}")
print(f"CP1 TG rows: {len(cp1_tg)}")

print(f"\nCP1 GT FrameID range: {cp1_gt['FrameID'].min()} - {cp1_gt['FrameID'].max()}")
print(f"CP1 TG FrameID range: {cp1_tg['FrameID'].min()} - {cp1_tg['FrameID'].max()}")

# Check Frame 1 data
print("\n--- Frame 1 Comparison ---")
f1_gt = cp1_gt[cp1_gt['FrameID']==1].sort_values('Idx')
f1_tg = cp1_tg[cp1_tg['FrameID']==1].sort_values('Idx')

print(f"Frame 1 GT count: {len(f1_gt)}, TG count: {len(f1_tg)}")

if not f1_gt.empty and not f1_tg.empty:
    print("\nFirst 10 GT values (Frame 1):")
    print(f1_gt.head(10)[['Idx', 'Val']].to_string(index=False))
    
    print("\nFirst 10 TG values (Frame 1):")
    print(f1_tg.head(10)[['Idx', 'Val']].to_string(index=False))
    
    # Merge to compare
    merged = pd.merge(f1_gt, f1_tg, on=['FrameID', 'Idx'], suffixes=('_GT', '_TG'))
    merged['AbsErr'] = np.abs(merged['Val_GT'] - merged['Val_TG'])
    
    print(f"\nMax Abs Error in Frame 1: {merged['AbsErr'].max():.6f}")
    print(f"Mean Abs Error in Frame 1: {merged['AbsErr'].mean():.6f}")
    
    # Check if it's simply a matter of different landmark values
    print("\n--- Hypothesis: Same frame, different landmark detection? ---")
    print(f"GT Frame 1 Idx 0 (x_0): {f1_gt[f1_gt['Idx']==0]['Val'].values[0]:.4f}")
    print(f"TG Frame 1 Idx 0 (x_0): {f1_tg[f1_tg['Idx']==0]['Val'].values[0]:.4f}")
    
    # Are these landmarks from different detections?
    # The test_bash1.csv might have been regenerated by FeatureExtraction
    # but RecoverAU reads the SAME file...
    
print("\n--- Hypothesis: RecoverAU reads different file than FeatureExtraction wrote? ---")
print("Check if test_bash1.csv was updated by FeatureExtraction...")
print("RecoverAU reads: samples/recover_au_test/test_bash1.csv")
print("FeatureExtraction writes to: samples/recover_au_test/ (with -out_dir)")

# Check the actual landmark file
import os
csv_path = "samples/recover_au_test/test_bash1.csv"
if os.path.exists(csv_path):
    print(f"\ntest_bash1.csv exists, modified: {os.path.getmtime(csv_path)}")
    df_csv = pd.read_csv(csv_path)
    print(f"CSV columns: {list(df_csv.columns[:10])}...")
    print(f"CSV rows: {len(df_csv)}")
    
    # Check if x_0 matches
    if 'x_0' in df_csv.columns:
        x0_csv = df_csv['x_0'].values[0]  # First frame
        print(f"CSV Frame 0 x_0: {x0_csv:.4f}")
        print(f"TG Frame 1 Idx 0: {f1_tg[f1_tg['Idx']==0]['Val'].values[0]:.4f}")
        print(f"Match: {abs(x0_csv - f1_tg[f1_tg['Idx']==0]['Val'].values[0]) < 0.001}")
