# Final Verification Script: Official OpenFace vs Local RecoverAU
# Usage: .\final_test_official.ps1 [VideoName]

param (
    [string]$VideoName = "test_Mizuno"
)

$ErrorActionPreference = "Continue"

# --- CONFIGURATION (PATHS) ---
# Use PSScriptRoot to get the directory where the script is saved
$ScriptDir = $PSScriptRoot
# Resolve to absolute path to remove '..'
$RootDir = Resolve-Path "$ScriptDir\..\..\.." | Select-Object -ExpandProperty Path
$SampleDir = "$RootDir\samples\recover_au_test"
$FinalTestDir = "$SampleDir\final_test"

# Official FeatureExtraction (Ground Truth Generator)
$OfficialFE = "C:\Users\kishibashi\OpenFace_2.2.0_win_x64\FeatureExtraction.exe"

# Local RecoverAU (Target)
$LocalRecoverAU = "$RootDir\x64\Release\RecoverAU.exe"

# Input Video
$VideoPath = "$SampleDir\$VideoName.MOV"
# Fallback to MP4 if MOV not found
if (-not (Test-Path $VideoPath)) {
    $VideoPath = "$SampleDir\$VideoName.mp4"
}

# Output Paths
$GtDir = "$FinalTestDir\gt_output"
$HogPath = "$GtDir\$VideoName.hog"
$GtCsvPath = "$GtDir\$VideoName.csv"
$TrackedVideoPath = "$GtDir\${VideoName}.avi"

$TargetCsvPath = "$FinalTestDir\${VideoName}_recovered.csv"
$NoAuCsvPath = "$FinalTestDir\${VideoName}_noAU.csv"

# --- CHECK PRE-REQUISITES ---
if (-not (Test-Path $OfficialFE)) {
    Write-Error "Official FeatureExtraction not found at $OfficialFE"
    exit 1
}
if (-not (Test-Path $LocalRecoverAU)) {
    Write-Error "Local RecoverAU not found at $LocalRecoverAU"
    exit 1
}
if (-not (Test-Path $VideoPath)) {
    Write-Error "Video not found at $VideoPath"
    exit 1
}

# Create Output Directory
if (-not (Test-Path $GtDir)) { New-Item -ItemType Directory -Path $GtDir | Out-Null }

Write-Host "==========================================================" -ForegroundColor Yellow
Write-Host " FINAL TEST: Official OpenFace vs Local RecoverAU" -ForegroundColor Yellow
Write-Host " Video: $VideoName" -ForegroundColor Yellow
Write-Host "==========================================================`n"

# --- STEP 1: GENERATE GROUND TRUTH (OFFICIAL OPENFACE) ---
Write-Host "[1/4] Running Official FeatureExtraction..." -ForegroundColor Cyan
# Arguments: -f <video> -out_dir <dir> -2Dfp -3Dfp -aus -pose -hogalign -tracked (for AVI)
# -hogalign is crucial for generating the .hog file
$FeatArgs = "-f", "`"$VideoPath`"", "-out_dir", "`"$GtDir`"", "-2Dfp", "-3Dfp", "-aus", "-pose", "-hogalign", "-tracked"

Write-Host "Command: $OfficialFE $FeatArgs"
Start-Process -FilePath $OfficialFE -ArgumentList $FeatArgs -Wait -NoNewWindow
if (-not (Test-Path $HogPath)) {
    Write-Error "HOG file not generated by Official FE."
    exit 1
}
if (-not (Test-Path $TrackedVideoPath)) {
    Write-Warning "Tracked AVI file might not have been generated (codec issue?). Continuing."
}
else {
    Write-Host "  Generated Tracked Video: $TrackedVideoPath" -ForegroundColor Green
}

# --- STEP 2: PREPARE INPUT (DROP AU COLUMNS) ---
Write-Host "`n[2/4] Preparing Input (Dropping AUs from GT CSV)..." -ForegroundColor Cyan
try {
    $DropAuScript = "$RootDir\drop_au_columns.py"
    python "$DropAuScript" "$GtCsvPath" "$NoAuCsvPath"
    if (-not (Test-Path $NoAuCsvPath)) { throw "Output CSV not created" }
    Write-Host "  Created stripped CSV: $NoAuCsvPath" -ForegroundColor Green
}
catch {
    Write-Error "Failed to drop AU columns."
    exit 1
}

# --- STEP 3: RUN LOCAL RECOVER AU ---
Write-Host "`n[3/4] Running Local RecoverAU..." -ForegroundColor Cyan
if (Test-Path $TargetCsvPath) { Remove-Item $TargetCsvPath }

# Arguments: -f <hog> -l <csv_no_au> -out_dir <dir>
# RecoverAU expects args: hog_path landmark_path output_path (based on previous usages)
# Wait, RecoverAU arguments in previous scripts were:
# & $RecovCmd $HogPath $LandmarkCsvPath $RecoverOutCsv
# But RecoverAU source code main() uses: 
# arguments = get_arguments(argc, argv); -> -f, -l, -out_dir flags usually?
# Let's check RecoverAU.cpp usage help if possible, but previous script used:
# $RecovArgs = "$HogPath", "$LandmarkCsvNoAuPath", "$RecoverOutCsv"
# Actually pipeline_test.ps1 lines 83-86 use simple positional args? NO.
# pipeline_test.ps1 line 59 uses named args for FE.
# line 83 uses positional for Recov? No, wait.
# pipeline_test.ps1 says: $RecovArgs = "$HogPath", "$LandmarkCsvPath", "$RecoverOutCsv"
# AND THEN & $RecovCmd $HogPath $LandmarkCsvPath $RecoverOutCsv
# BUT RecoverAU code uses `vector<string> arguments = get_arguments(argc, argv);` and looks for "-f", "-l".
# Let's stick to the args format used in pipeline_test.ps1 which seemed to work.
# Wait, pipeline_test.ps1 used:
# $RecovCmd = "$BinDir\RecoverAU.exe"
# Start-Process ... -ArgumentList "-f `"$HogPath`" -l `"$LandmarkCsvPath`" -out_dir `"$SampleDir`""
# Ah, line 140 replacement showed:
# $RecoverArgs = "-f `"$HogPath`" -l `"$LandmarkCsvNoAuPath`" -out_dir `"$SampleDir`""
# OK, so it uses FLAGGED arguments.

# Arguments: <hog> <csv_no_au> <output_csv> (POSITIONAL)
# RecoverAU.cpp main() uses argv[1], argv[2], argv[3]
$RecoverArgs = $HogPath, $NoAuCsvPath, $TargetCsvPath

Write-Host "Command: $LocalRecoverAU $RecoverArgs"
Start-Process -FilePath $LocalRecoverAU -ArgumentList $RecoverArgs -Wait -NoNewWindow

# The output filename matches the *HOG* filename usually + suffix? 
# RecoverAU usually outputs <VideoName>.csv or similar?
# If input was test_Mizuno.hog, output is usually test_Mizuno_recovered.csv if code logic adds suffix?
# Let's verify output file existence.
# If RecoverAU outputs to out_dir, it likely keeps the basename.
# It seems to output `test_Mizuno_recovered.csv` if logic adds `_recovered`.
# Or maybe just `test_Mizuno.csv`?
# Let's assume it matches `test_Mizuno_recovered.csv` if we check `RecoverAU.cpp` logic?
# Actually, the user's `RecoverAU.cpp` writes to `out_file`. The filename is derived.
# Assuming it works like previous tests, it writes to `${VideoName}_recovered.csv`.
$ExpectedOutput = "$FinalTestDir\${VideoName}_recovered.csv"
if (-not (Test-Path $ExpectedOutput)) {
    # Try alternate name
    $ExpectedOutput = "$FinalTestDir\${VideoName}.csv"
    if (-not (Test-Path $ExpectedOutput)) {
        Write-Error "RecoverAU output not found in $FinalTestDir"
        exit 1
    }
}
Write-Host "  Generated Output: $ExpectedOutput" -ForegroundColor Green

# --- STEP 4: VERIFY RESULTS ---
Write-Host "`n[4/4] Verifying Results (Accuracy/F1)..." -ForegroundColor Cyan
$VerifyScript = "$RootDir\verify_recovery.py"

# python verify_recovery.py compare --gt <gt_csv> --rec <rec_csv> --out <dir> ...
$VerifyArgs = "compare", "--gt", "`"$GtCsvPath`"", "--rec", "`"$ExpectedOutput`"", "--out", "`"$FinalTestDir`"", "--min_corr", "0.99", "--tolerance", "0.1"

python "$VerifyScript" compare --gt "$GtCsvPath" --rec "$ExpectedOutput" --out "$FinalTestDir" --min_corr 0.99 --tolerance 0.1

if ($LASTEXITCODE -eq 0) {
    Write-Host "`n[SUCCESS] Final Test Passed!" -ForegroundColor Green
}
else {
    Write-Host "`n[FAILURE] Final Test Failed." -ForegroundColor Red
}
